(function () {
  "use strict";
  var config=window.BUYBOX_CONFIG,key="",offset=0,nextOffset=null,rows=[],selected=new Set(),busy=false;
  var byId=id=>document.getElementById(id);
  var esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  try{key=sessionStorage.getItem(config.accessSessionKey)||"";}catch(_){}
  if(!key){window.AppAuth.redirect(false);return;}
  function message(value){byId("cancellationStatus").textContent=value||"";}
  function dateTime(value){if(!value)return "Mai";try{return new Date(value).toLocaleString("it-IT");}catch(_){return value;}}
  async function api(path,payload){var response=await fetch(config.apiBase+path,{method:payload===undefined?"GET":"POST",headers:{"X-App-Key":key,"Content-Type":"application/json"},body:payload===undefined?undefined:JSON.stringify(payload),cache:"no-store",credentials:"omit"});var data={};try{data=await response.json();}catch(_){}if(response.status===401){try{sessionStorage.removeItem(config.accessSessionKey);}catch(_){}window.AppAuth.redirect(false);throw new Error("Codice di accesso richiesto");}if(!response.ok)throw new Error(data.error||"Operazione non riuscita");return data;}
  function setBusy(value){busy=value;document.body.classList.toggle("is-working",value);byId("syncCancellations").disabled=value;byId("activateCancellations").disabled=value;updateCreateButton();}
  function updateCreateButton(){var count=selected.size;byId("createRestore").disabled=busy||count===0;byId("createRestore").textContent=count?"Crea ordine di ripristino · "+count:"Crea ordine di ripristino";}
  function params(){var value=new URLSearchParams({q:byId("cancellationQuery").value.trim(),from:byId("cancellationFrom").value,to:byId("cancellationTo").value,status:byId("cancellationState").value,offset:String(offset)});return value.toString();}
  function render(){
    if(!rows.length){byId("cancellationResults").innerHTML='<div class="cancellation-empty"><strong>Nessun annullamento in questo filtro</strong><span>Premi “Cerca nuovi annullamenti” per aggiornare i dati da Back Market.</span></div>';return;}
    var selectable=byId("cancellationState").value!=="assigned";
    var body=rows.map(row=>{var pending=row.processing_status==="pending",checked=selected.has(Number(row.orderline_id));var state=pending?'Da ripristinare':row.processing_status==="assigned"?'Inserito in un ordine':'Inventario iniziale';var detail=row.restoration_order_key?'<a href="lavorazione.html?key='+encodeURIComponent(row.restoration_order_key)+'">Apri ordine →</a>':'';return '<tr><td>'+(pending&&selectable?'<input type="checkbox" data-select="'+row.orderline_id+'" aria-label="Seleziona orderline '+row.orderline_id+'" '+(checked?'checked':'')+'>':'')+'</td><td>'+esc(dateTime(row.order_modified_at))+'</td><td><strong>'+esc(row.order_id)+'</strong></td><td>'+esc(row.orderline_id)+'</td><td><strong>'+esc(row.sku_snapshot)+'</strong><small>ID inserzione: '+esc(row.listing_id)+'</small></td><td>'+esc(row.product_snapshot)+'</td><td class="numeric"><strong>'+esc(row.quantity)+'</strong></td><td><span class="item-state '+(pending?'pending':'done')+'">'+esc(state)+'</span>'+detail+'</td></tr>';}).join("");
    byId("cancellationResults").innerHTML='<div class="purchases-table-wrap cancellation-table-wrap"><table class="cancellation-table"><thead><tr><th><input id="selectVisible" type="checkbox" aria-label="Seleziona tutte le righe visibili"></th><th>Data annullamento</th><th>Ordine</th><th>Orderline ID</th><th>SKU</th><th>Prodotto</th><th>Quantità</th><th>Stato</th></tr></thead><tbody>'+body+'</tbody></table></div>';
    var allPending=rows.filter(row=>row.processing_status==="pending");var allChecked=allPending.length&&allPending.every(row=>selected.has(Number(row.orderline_id)));byId("selectVisible").checked=Boolean(allChecked);byId("selectVisible").disabled=!allPending.length;
  }
  async function loadRows(append){if(!append){offset=0;rows=[];selected.clear();}var data=await api("/api/cancellations/items?"+params());rows=append?rows.concat(data.results):data.results;nextOffset=data.next_offset;byId("cancellationMore").hidden=nextOffset===null;render();updateCreateButton();}
  async function refreshStatus(){var data=await api("/api/cancellations/status");byId("activationPanel").hidden=data.activated;byId("cancellationWorkspace").hidden=!data.activated;if(!data.activated){message("Il monitoraggio non è ancora attivo.");return false;}byId("pendingCount").textContent=data.counts.pending||0;byId("assignedCount").textContent=data.counts.assigned||0;var state=data.state||{};byId("lastSync").textContent=state.sync_status==="running"?"Sincronizzazione da continuare":state.last_success_at?"Ultimo controllo: "+dateTime(state.last_success_at):"Pronto per il primo controllo";return true;}
  byId("activateCancellations").addEventListener("click",async()=>{if(busy||!confirm("Da questo momento verranno registrati solo i nuovi annullamenti cliente. Le cancellazioni precedenti resteranno escluse. Confermi il punto di partenza?"))return;setBusy(true);try{await api("/api/cancellations/activate",{confirm:true});message("Monitoraggio attivato. Nessuna quantità è stata modificata.");await refreshStatus();await loadRows(false);}catch(error){message(error.message);}finally{setBusy(false);}});
  byId("syncCancellations").addEventListener("click",async()=>{if(busy)return;setBusy(true);message("Lettura degli ordini modificati da Back Market…");try{var result=await api("/api/cancellations/sync",{});message(result.complete?"Controllo completato. Nessuna quantità è stata modificata.":"Prima parte completata: premi di nuovo per continuare la sincronizzazione.");await refreshStatus();await loadRows(false);}catch(error){message(error.message);}finally{setBusy(false);}});
  byId("cancellationFilters").addEventListener("submit",event=>{event.preventDefault();if(!busy)loadRows(false).catch(error=>message(error.message));});
  byId("cancellationReset").addEventListener("click",()=>{byId("cancellationQuery").value="";byId("cancellationFrom").value="";byId("cancellationTo").value="";byId("cancellationState").value="pending";loadRows(false).catch(error=>message(error.message));});
  byId("cancellationMore").addEventListener("click",()=>{offset=nextOffset;loadRows(true).catch(error=>message(error.message));});
  document.addEventListener("change",event=>{if(event.target.matches("[data-select]")){var id=Number(event.target.dataset.select);event.target.checked?selected.add(id):selected.delete(id);updateCreateButton();}if(event.target.id==="selectVisible"){rows.filter(row=>row.processing_status==="pending").forEach(row=>event.target.checked?selected.add(Number(row.orderline_id)):selected.delete(Number(row.orderline_id)));render();updateCreateButton();}});
  byId("createRestore").addEventListener("click",async()=>{if(busy||!selected.size)return;var units=rows.filter(row=>selected.has(Number(row.orderline_id))).reduce((sum,row)=>sum+Number(row.quantity),0);if(!confirm("Creare un ordine di ripristino con "+selected.size+" cancellazioni e "+units+" unità?\n\nLa creazione non aggiorna Back Market e non modifica prezzi o costi."))return;setBusy(true);try{var result=await api("/api/cancellations/restore",{orderline_ids:[...selected],confirm:true});message("Ordine "+result.order_number+" creato. Nessuna quantità è stata inviata.");location.href="lavorazione.html?key="+encodeURIComponent(result.order_key);}catch(error){message(error.message);await loadRows(false);}finally{setBusy(false);}});
  (async()=>{try{if(await refreshStatus())await loadRows(false);}catch(error){message(error.message);}})();
}());
