(function(){
  "use strict";
  var config=window.BUYBOX_CONFIG,key="",batch=null,sourceRequest=null,catalog=null,currentMapping=null,historyRows=[],offset=null,busy=false;
  var byId=id=>document.getElementById(id);
  var esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  var displayDate=value=>{var match=String(value||"").match(/^(\d{4})-(\d{2})-(\d{2})$/);return match?match[3]+"/"+match[2]+"/"+match[1]:String(value||"—");};
  try{key=sessionStorage.getItem(config.accessSessionKey)||"";}catch(_){}
  function message(value){byId("returnStatus").textContent=value;}
  function accessState(){byId("returnWorkspace").hidden=!key;if(!key)window.AppAuth.redirect(false);}
  async function api(path,body){
    var response=await fetch(config.apiBase+path,{method:body===undefined?"GET":"POST",headers:{"X-App-Key":key,"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body),cache:"no-store",credentials:"omit"});
    var data={};try{data=await response.json();}catch(_){}
    if(response.status===401){try{sessionStorage.removeItem(config.accessSessionKey);}catch(_){}window.AppAuth.redirect(true);throw new Error("Codice di accesso richiesto");}
    if(!response.ok)throw new Error(data.error||"Operazione non riuscita");return data;
  }
  async function run(action){if(busy)return;busy=true;document.body.classList.add("is-working");try{await action();}catch(error){message(error.message||"Operazione non riuscita");}finally{busy=false;document.body.classList.remove("is-working");}}
  function linesTable(lines){return '<div class="purchases-table-wrap"><table class="returns-preview-table"><thead><tr><th>Codice Ready</th><th>Prodotto</th><th>Quantità</th><th>Inserzione Back Market</th><th>Azioni</th></tr></thead><tbody>'+lines.map(line=>'<tr><td><strong>'+esc(line.ready_code)+'</strong><small>Righe '+esc(line.source_rows.join(" · "))+'</small></td><td>'+esc(line.description)+'</td><td><strong>'+line.quantity+'</strong></td><td>'+(line.mapping?'<span class="mapping-state">Abbinato</span><small>'+esc(line.mapping.sku)+'</small>':'<span class="mapping-state removed">Da abbinare</span>')+'</td><td><button type="button" data-return-map="'+esc(line.ready_code)+'">'+(line.mapping?'Modifica':'Abbina')+'</button></td></tr>').join("")+'</tbody></table></div>';}
  function renderPreview(){
    if(!batch){byId("returnPreview").replaceChildren();return;}
    var duplicate=batch.status==="duplicate";
    var state=duplicate?'File già salvato come '+batch.load_number:batch.missing?batch.missing+' articoli da abbinare':'Pronto per il salvataggio';
    byId("returnPreview").innerHTML='<section class="purchases-panel return-preview-panel"><div class="returns-panel-head"><div><span class="eyebrow">Anteprima carico</span><h2>Carico resi '+esc(displayDate(batch.date))+'</h2><p>'+batch.row_count+' righe · '+batch.line_count+' articoli · '+batch.units+' pezzi</p></div><span class="order-state '+(duplicate?'done':'pending')+'">'+esc(state)+'</span></div>'+linesTable(batch.lines)+(duplicate?'<a class="primary-button" href="lavorazione.html?key='+encodeURIComponent(batch.order_key)+'">Apri carico salvato</a>':'<button type="button" data-save-return '+(!batch.token?'disabled':'')+'>Salva carico resi</button><small>Il salvataggio non invia quantità a Back Market.</small>')+'</section>';
  }
  async function loadPreview(){
    batch=null;byId("returnPreview").replaceChildren();message("Lettura e controllo del file resi…");
    var data=await api("/api/returns/preview",sourceRequest);batch=data.batch;
    byId("returnPreviewSource").textContent="Origine: "+data.source.name+" · anteprima non ancora salvata.";renderPreview();
    message(batch.missing?"Completa gli abbinamenti mancanti.":batch.status==="duplicate"?"Questo file è già presente: nessun doppio carico.":"Controllo completato. Salva il carico quando sei pronto.");
  }
  async function history(append){
    var data=await api("/api/returns/loads?offset="+(append?offset||0:0));historyRows=append?historyRows.concat(data.results):data.results;offset=data.next_offset;byId("returnHistoryMore").hidden=offset===null;
    if(!historyRows.length){byId("returnHistory").innerHTML='<div class="return-empty">Nessun carico resi salvato.</div>';return;}
    byId("returnHistory").innerHTML='<div class="purchases-table-wrap"><table class="order-table"><thead><tr><th>Carico</th><th>Data</th><th>Articoli</th><th>Pezzi</th><th>Stato</th><th>Azioni</th></tr></thead><tbody>'+historyRows.map(row=>{var complete=row.processed_items>=row.line_count&&!row.pending_items,state=complete?'Completato':row.processed_items?'In lavorazione':'Da caricare';return '<tr><td><span class="order-kind quantity">Solo quantità</span><strong>'+esc(row.load_number)+'</strong><small>'+esc(row.source_name)+'</small></td><td>'+esc(displayDate(row.load_date))+'</td><td>'+row.line_count+'</td><td>'+row.units+'</td><td><span class="order-state '+(complete?'done':'pending')+'">'+state+'</span></td><td><a class="table-action" href="lavorazione.html?key='+encodeURIComponent(row.order_key)+'">'+(complete?'Rivedi':'Carica')+'</a><button type="button" data-return-detail="'+esc(row.order_key)+'">Dettagli</button></td></tr>';}).join("")+'</tbody></table></div>';
  }
  function filterListings(){var words=byId("returnListingSearch").value.toLowerCase().trim().split(/\s+/).filter(Boolean);var matches=(catalog||[]).filter(item=>words.every(word=>(item.sku+" "+(item.title||item.product?.title||"")).toLowerCase().includes(word)));var select=byId("returnListingChoice");select.replaceChildren();matches.slice(0,50).forEach(item=>{var option=document.createElement("option");option.value=String(item.id);option.textContent=item.sku;select.appendChild(option);});select.selectedIndex=-1;byId("returnListingCount").textContent=matches.length>50?"Primi 50 risultati su "+matches.length:matches.length+" risultati";}
  async function openMapping(code){var line=batch?.lines.find(item=>item.ready_code===code);if(!line)return;currentMapping=line;message("Caricamento catalogo Back Market…");if(!catalog){var data=await api("/api/catalog");catalog=data.results.filter(item=>item.id&&typeof item.sku==="string");}byId("returnMappingContext").textContent=line.ready_code+" — "+line.description;byId("returnMappingCurrent").textContent="Abbinamento attuale: "+(line.mapping?.sku||"nessuno");byId("returnMappingError").textContent="";byId("returnListingSearch").value="";filterListings();byId("returnMappingDialog").showModal();message("Seleziona lo SKU esatto e conferma.");}
  byId("readReturnsDrive").addEventListener("click",()=>run(async()=>{sourceRequest={source:"drive"};await loadPreview();}));
  byId("returnFile").addEventListener("change",event=>run(async()=>{var file=event.target.files[0];if(!file)return;if(file.size>2*1024*1024)throw new Error("Il file supera 2 MiB.");var bytes=await file.arrayBuffer(),csv;try{csv=new TextDecoder("utf-8",{fatal:true}).decode(bytes);}catch(_){csv=new TextDecoder("windows-1252").decode(bytes);}sourceRequest={source:"upload",name:file.name,csv};await loadPreview();}));
  byId("returnListingSearch").addEventListener("input",filterListings);
  byId("returnMappingCancel").addEventListener("click",()=>byId("returnMappingDialog").close());
  byId("returnDetailClose").addEventListener("click",()=>byId("returnDetailDialog").close());
  byId("returnHistoryMore").addEventListener("click",()=>run(()=>history(true)));
  byId("returnMappingForm").addEventListener("submit",event=>{event.preventDefault();run(async()=>{var listingId=byId("returnListingChoice").value;if(!listingId||!currentMapping)return;var selected=catalog.find(item=>String(item.id)===listingId);if(!confirm("Confermi "+currentMapping.ready_code+" → "+selected.sku+"?\nL’abbinamento sarà condiviso con Acquisti."))return;try{await api("/api/mappings/save",{ready_code:currentMapping.ready_code,ready_description:currentMapping.description,expected_revision:currentMapping.mapping_revision,listing_id:listingId,confirm:true});}catch(error){byId("returnMappingError").textContent=error.message;throw error;}byId("returnMappingDialog").close();await loadPreview();});});
  document.addEventListener("click",event=>{var target=event.target.closest("button");if(!target)return;if(target.dataset.returnMap)run(()=>openMapping(target.dataset.returnMap));if(target.hasAttribute("data-save-return"))run(async()=>{if(!batch?.token)return;if(!confirm("Salvare Carico resi "+displayDate(batch.date)+"?\n"+batch.units+" pezzi.\n\nLe quantità Back Market NON saranno ancora aggiornate."))return;var saved=await api("/api/returns/confirm",{token:batch.token,confirm:true});batch.status="duplicate";batch.order_key=saved.order_key;batch.load_number=saved.load_number;batch.token=null;renderPreview();await history(false);message(saved.duplicate?"Carico già salvato: nessun duplicato creato.":saved.load_number+" salvato online. Aprilo per caricare le quantità.");});if(target.dataset.returnDetail)run(async()=>{var detail=await api("/api/purchases/document?key="+encodeURIComponent(target.dataset.returnDetail));byId("returnDetailTitle").textContent=detail.document_label+" · "+detail.document_number;byId("returnDetailContent").innerHTML='<p>'+detail.units+' pezzi. Nessun costo o prezzo associato.</p><div class="purchases-table-wrap"><table><thead><tr><th>SKU</th><th>Prodotto</th><th>Quantità</th><th>Documenti Ready</th></tr></thead><tbody>'+detail.lines.map(line=>'<tr><td>'+esc(line.sku_snapshot)+'</td><td>'+esc(line.description)+'</td><td>'+line.incoming_quantity+'</td><td>'+esc((line.source_references||[]).join(" · "))+'</td></tr>').join("")+'</tbody></table></div>';byId("returnDetailDialog").showModal();});});
  accessState();if(key)run(async()=>{await api("/api/returns/status");await history(false);message("Archivio resi online disponibile.");});
})();
