(function(){
  "use strict";
  var config=window.BUYBOX_CONFIG||{}, core=window.BuyboxCore, valuation=window.StockValuationCore;
  var state={listings:[],families:[],selectedFamily:null,currentJob:null,busy:false};
  function byId(id){return document.getElementById(id);}
  function esc(value){return String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}
  function key(){try{return sessionStorage.getItem(config.accessSessionKey)||"";}catch{return "";}}
  async function api(path,options){options=options||{};var headers=new Headers({Accept:"application/json"});headers.set("X-App-Key",key());if(options.body!==undefined)headers.set("Content-Type","application/json");var response=await fetch(config.apiBase.replace(/\/$/,"")+path,{method:options.method||"GET",headers:headers,body:options.body===undefined?undefined:JSON.stringify(options.body),cache:"no-store"});var data={};try{data=await response.json();}catch{}if(response.status===401){window.AppAuth.redirect(true);throw new Error("Accesso scaduto");}if(!response.ok){var error=new Error(data.error||"Servizio non disponibile");error.code=data.code;throw error;}return data;}
  function message(value,tone){byId("captureMessage").textContent=value||"";byId("captureMessage").dataset.tone=tone||"";}
  function setBusy(value){state.busy=value;document.querySelectorAll("button").forEach(function(button){button.disabled=value;});}
  function money(value,currency){return new Intl.NumberFormat("it-IT",{style:"currency",currency:currency||"EUR"}).format(Number(value));}
  function dateTime(value){return value?new Intl.DateTimeFormat("it-IT",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"—";}
  function statusLabel(value){return ({prepared:"Preparata",active:"Attiva temporaneamente",capturing:"Lettura in corso",restoring:"Ripristino in corso",restore_required:"Ripristino richiesto",restored:"Ripristinata"})[value]||value;}

  async function loadStatus(){
    var data=await api("/api/buybox-captures/status"), open=data.open||[];
    byId("recoveryPanel").hidden=!open.length;
    if(open.length){var item=open[0];byId("recoveryDescription").textContent=item.sku_snapshot+" · "+statusLabel(item.status)+". Prima di iniziare altro, completa o ripristina questa operazione.";byId("resumeCapture").dataset.job=item.job_id;byId("restoreNow").dataset.job=item.job_id;}
    byId("captureHistory").innerHTML=(data.recent||[]).length?'<div class="capture-history-table"><table><thead><tr><th>Inserzione</th><th>Rilevata</th><th>Stato</th><th></th></tr></thead><tbody>'+data.recent.map(function(item){return '<tr><td><strong>'+esc(item.product_snapshot)+'</strong><small>'+esc(item.sku_snapshot)+'</small></td><td>'+esc(dateTime(item.captured_at||item.created_at))+'</td><td><span class="capture-status restored">Ripristinata</span></td><td><button type="button" class="table-link" data-open-job="'+esc(item.job_id)+'">Apri</button></td></tr>';}).join("")+'</tbody></table></div>':'<p class="capture-empty-row">Nessuna rilevazione completata.</p>';
  }
  async function loadCatalog(force){
    byId("captureCatalogStatus").textContent=force?"Aggiornamento catalogo…":"Connessione al catalogo…";
    var data=await api("/api/catalog"+(force?"?refresh=1":""));
    state.listings=(data.results||[]).map(core.normalizeListing).filter(function(item){return item.id&&Number(item.quantity)===0&&valuation.eligibleForValuation(item);});
    state.families=valuation.groupFamilies(state.listings);renderFamilies();
    byId("captureCatalogStatus").textContent=state.listings.length+" inserzioni esaurite in "+state.families.length+" famiglie.";
  }
  function matchingFamilies(){var query=core.normalizeSearchText(byId("captureSearch").value),tokens=query.split(" ").filter(Boolean);return state.families.filter(function(group){var hay=core.normalizeSearchText(group.label+" "+group.listings.map(function(row){return row.sku;}).join(" "));return tokens.every(function(token){return hay.indexOf(token)>=0;});}).slice(0,12);}
  function renderFamilies(){
    if(state.selectedFamily)return;
    var rows=matchingFamilies();byId("captureFamilies").hidden=false;byId("captureListings").hidden=true;
    byId("captureFamilies").innerHTML=rows.map(function(group){return '<button type="button" data-family="'+esc(group.key)+'"><strong>'+esc(group.label)+'</strong><span>'+group.listings.length+' inserzioni a quantità zero</span></button>';}).join("")||'<p class="capture-empty-row">Nessuna famiglia trovata.</p>';
  }
  function openFamily(familyKey){state.selectedFamily=state.families.find(function(row){return row.key===familyKey;});if(!state.selectedFamily)return;byId("captureFamilies").hidden=true;var box=byId("captureListings");box.hidden=false;box.innerHTML='<div class="capture-family-head"><button type="button" data-back-family>← Famiglie</button><strong>'+esc(state.selectedFamily.label)+'</strong></div><div class="capture-listing-table"><table><thead><tr><th>Inserzione</th><th>Variante</th><th>Quantità</th><th></th></tr></thead><tbody>'+state.selectedFamily.listings.map(function(item){return '<tr><td><strong>'+esc(item.title)+'</strong><small>'+esc(item.sku)+'</small></td><td>'+esc(item.quality+' · '+item.batteryLabel)+'</td><td>0</td><td><button type="button" data-prepare="'+esc(item.id)+'">Prepara</button></td></tr>';}).join("")+'</tbody></table></div>';}
  function closeFamily(){state.selectedFamily=null;renderFamilies();}
  function renderJob(data){
    var job=data.job||data, rows=data.markets||job.markets||[], observations=data.observations||job.observations||[];state.currentJob=job;
    byId("captureEmpty").hidden=true;byId("captureJob").hidden=false;byId("captureJobTitle").textContent=job.product_snapshot||job.product||"Inserzione Back Market";byId("captureJobSku").textContent=job.sku_snapshot||job.sku||job.listing_id;var status=job.status||data.status;byId("captureJobStatus").textContent=statusLabel(status);byId("captureJobStatus").className="capture-status "+status;
    byId("captureMarketTable").innerHTML=rows.length?'<table><thead><tr><th>Mercato</th><th>Originale min</th><th>Originale target</th><th>Temporaneo</th><th>Massimo BM</th></tr></thead><tbody>'+rows.map(function(row){return '<tr><td><strong>'+esc(row.market)+'</strong></td><td>'+esc(money(row.original_min_price,row.currency))+'</td><td>'+esc(money(row.original_price,row.currency))+'</td><td>'+esc(money(row.temporary_price,row.currency))+'</td><td>'+esc(money(row.max_price,row.currency))+'</td></tr>';}).join("")+'</tbody></table>':"";
    var valid=observations.filter(function(row){return row.classification==="competitive";}).length, excluded=observations.length-valid;
    byId("captureSummary").innerHTML=observations.length?'<strong>'+valid+' mercati con riferimento competitivo</strong><span>'+excluded+' esclusi perché senza dato valido o con nostra offerta vincente.</span>':'<strong>Snapshot originale salvato online</strong><span>I prezzi temporanei non saranno mai usati come riferimento economico.</span>';
    byId("activateCapture").hidden=status!=="prepared";byId("readCapture").hidden=status!=="active";byId("manualRestore").hidden=!(["active","capturing","restoring","restore_required"].includes(status));
  }
  async function openJob(jobId){var data=await api("/api/buybox-captures/status?job_id="+encodeURIComponent(jobId));renderJob(data);}
  async function prepareListing(listingId){if(state.busy)return;if(!confirm("Preparare la rilevazione? Questa fase legge e salva i prezzi originali, ma non modifica Back Market."))return;setBusy(true);message("Controllo dei 12 mercati…");try{var data=await api("/api/buybox-captures/prepare",{method:"POST",body:{listing_id:listingId,confirm:true}});await openJob(data.job_id);message("Controllo completato: nessuna modifica effettuata.","ok");await loadStatus();}catch(error){message(error.message,"bad");}finally{setBusy(false);}}
  async function activate(){if(state.busy||!state.currentJob)return;if(!confirm("Confermi l’attivazione temporanea? I prezzi saranno portati al massimo consentito e la quantità a 1. Subito dopo dovrai leggere la BuyBox oppure ripristinare."))return;setBusy(true);message("Attivazione temporanea in corso…");try{await api("/api/buybox-captures/activate",{method:"POST",body:{job_id:state.currentJob.job_id,confirm:true}});await openJob(state.currentJob.job_id);message("Inserzione attiva temporaneamente. Attendi qualche secondo, poi leggi la BuyBox e ripristina.","warn");await loadStatus();}catch(error){message(error.message,"bad");await loadStatus();}finally{setBusy(false);}}
  async function capture(){if(state.busy||!state.currentJob)return;if(!confirm("Leggere ora le BuyBox e ripristinare subito quantità e prezzi originali?"))return;setBusy(true);message("Lettura e ripristino in corso…");try{var data=await api("/api/buybox-captures/capture",{method:"POST",body:{job_id:state.currentJob.job_id,confirm:true}});await openJob(state.currentJob.job_id);message("Rilevazione completata: "+data.competitive_markets+" mercati validi, inserzione ripristinata.","ok");await loadStatus();}catch(error){message(error.message+" Controlla subito il pannello di ripristino.","bad");await loadStatus();}finally{setBusy(false);}}
  async function restore(jobId){if(state.busy||!jobId)return;if(!confirm("Ripristinare subito quantità zero e tutti i prezzi originali?"))return;setBusy(true);message("Ripristino in corso…");try{await api("/api/buybox-captures/restore",{method:"POST",body:{job_id:jobId,confirm:true}});await openJob(jobId);message("Inserzione ripristinata e verificata.","ok");await loadStatus();}catch(error){message(error.message,"bad");await loadStatus();}finally{setBusy(false);}}
  function closeJob(){state.currentJob=null;byId("captureJob").hidden=true;byId("captureEmpty").hidden=false;}
  function bind(){byId("captureSearch").addEventListener("input",renderFamilies);byId("refreshCaptureCatalog").addEventListener("click",function(){loadCatalog(true).catch(function(error){message(error.message,"bad");});});byId("captureFamilies").addEventListener("click",function(event){var button=event.target.closest("[data-family]");if(button)openFamily(button.dataset.family);});byId("captureListings").addEventListener("click",function(event){var back=event.target.closest("[data-back-family]"),prepare=event.target.closest("[data-prepare]");if(back)closeFamily();if(prepare)prepareListing(prepare.dataset.prepare);});byId("activateCapture").addEventListener("click",activate);byId("readCapture").addEventListener("click",capture);byId("manualRestore").addEventListener("click",function(){restore(state.currentJob&&state.currentJob.job_id);});byId("closeCapture").addEventListener("click",closeJob);byId("resumeCapture").addEventListener("click",function(){openJob(this.dataset.job).catch(function(error){message(error.message,"bad");});});byId("restoreNow").addEventListener("click",function(){restore(this.dataset.job);});byId("captureHistory").addEventListener("click",function(event){var button=event.target.closest("[data-open-job]");if(button)openJob(button.dataset.openJob);});}
  async function start(){bind();try{await loadStatus();await loadCatalog(false);}catch(error){message(error.message,"bad");}}
  start();
})();
